// Generated by re/gen_globals.py - do not edit.
#pragma once
#include <stdint.h>
#include "../engine/ddw16.h"
#include "types.h"

struct ConvNode;
struct ConvHeader;
struct MenuItem;
struct Prefs;
struct SpawnDrop;
struct SpawnRecord;
struct MonsterStats;
struct MonsterTableEntry;
struct Wound;
struct MonsterCell;
struct Door;
struct InvSlot;
struct PlayerStats;
struct Player;
struct Equipment;
struct Projectile;
struct Rat;
struct Servant;
struct Trap;
struct Feature;
struct LevelItem;
struct Light;
struct LevelAux;
struct SampleInfo;
struct EVSound;
struct LevelObj;
struct Decal;
struct VisItem;
struct VisFeature;
struct VisDoor;
struct WallEntry;
struct TileEntry;
struct AnimTile;
struct Message;
struct Container;
struct Sparkle;
struct LevelLink;
struct SignText;
struct Book;
struct WarpTile;
struct TriggerSwitch;
struct TriggerGroup;
struct TrigWall;
struct TrigDoor;
struct TrigFeature;
struct TrigWarp;
struct TrigPos;
struct SaveHeader;
struct Burner;

struct ConvNode { // original size 0x1c
    int32_t topic; // +0x0
    int32_t state; // +0x4
    int32_t answer; // +0x8
    int32_t flags; // +0xc
    int32_t costText; // +0x10
    int32_t cost; // +0x14
    ConvNode * next; // +0x18
};

struct ConvHeader { // original size 0x18
    int32_t portrait; // +0x0
    ConvNode * first; // +0x4
    int32_t greeting; // +0x8
    int32_t farewell; // +0xc
    const char * voice; // +0x10
    int32_t voiceVariant; // +0x14
};

struct MenuItem { // original size 0x28
    const char * text; // +0x0
    uint16_t color; // +0x4
    int8_t hotkey; // +0x6
    int8_t pad0; // +0x7
    uint16_t hiColor; // +0x8
    int16_t pad1; // +0xa
    int32_t id; // +0xc
    int32_t x; // +0x10
    int32_t y; // +0x14
    int32_t left; // +0x18
    int32_t top; // +0x1c
    int32_t right; // +0x20
    int32_t bottom; // +0x24
};

struct Prefs { // original size 0x24
    int32_t cdVolume; // +0x0
    int32_t wavVolume; // +0x4
    int32_t flags; // +0x8
    int16_t mouseSpeed; // +0xc
    int16_t w0e; // +0xe
    int32_t shadows; // +0x10
    int32_t hints; // +0x14
    int32_t alwaysRun; // +0x18
    int32_t d1c; // +0x1c
    int32_t gamma; // +0x20
};
static_assert(sizeof(Prefs) == 0x24, "Prefs must keep the original layout");

struct SpawnDrop { // original size 0x4
    int16_t item; // +0x0
    int16_t qty; // +0x2
};
static_assert(sizeof(SpawnDrop) == 0x4, "SpawnDrop must keep the original layout");

struct SpawnRecord { // original size 0x1c
    int32_t x; // +0x0
    int32_t y; // +0x4
    uint8_t aiMode; // +0x8
    uint8_t type; // +0x9
    uint8_t b0a; // +0xa
    uint8_t b0b; // +0xb
    int32_t angle; // +0xc
    SpawnDrop drops[3]; // +0x10
};
static_assert(sizeof(SpawnRecord) == 0x1c, "SpawnRecord must keep the original layout");

struct MonsterStats { // original size 0xa0
    uint8_t dmgBase; // +0x0
    uint8_t dmgRange; // +0x1
    uint8_t defence; // +0x2
    uint8_t aiClass; // +0x3
    uint8_t dmgExtra; // +0x4
    uint8_t maxHp; // +0x5
    uint8_t b06; // +0x6
    uint8_t b07; // +0x7
    float moveStep; // +0x8
    int32_t idleDiv; // +0xc
    float radius; // +0x10
    float reach; // +0x14
    uint8_t b18; // +0x18
    uint8_t poisonChance; // +0x19
    uint8_t fearResist; // +0x1a
    uint8_t specialChance; // +0x1b
    uint8_t spellResist; // +0x1c
    uint8_t magicResist; // +0x1d
    uint8_t holdResist; // +0x1e
    uint8_t b1f; // +0x1f
    int32_t fireResist; // +0x20
    int32_t coldResist; // +0x24
    uint8_t b28; // +0x28
    uint8_t regenerates; // +0x29
    uint8_t drainChance; // +0x2a
    uint8_t ranged; // +0x2b
    uint8_t rangedDelay; // +0x2c
    uint8_t weaponLevel; // +0x2d
    uint8_t b2e; // +0x2e
    uint8_t b2f; // +0x2f
    int32_t acidic; // +0x30
    uint8_t regenRate; // +0x34
    uint8_t bloodType; // +0x35
    uint8_t corpse; // +0x36
    uint8_t b37; // +0x37
    int32_t opensDoors; // +0x38
    int32_t ignoresFloor; // +0x3c
    uint8_t attitude; // +0x40
    uint8_t b41; // +0x41
    uint8_t b42; // +0x42
    uint8_t b43; // +0x43
    int32_t fleeHp; // +0x44
    int32_t xp; // +0x48
    uint8_t flags; // +0x4c
    uint8_t attackAnim; // +0x4d
    uint8_t attackAnimCount; // +0x4e
    uint8_t rangedAnim; // +0x4f
    uint8_t deathAnim; // +0x50
    char amtName[16]; // +0x51
    char texName[19]; // +0x61
    const char * * name; // +0x74
    float scale; // +0x78
    int32_t idleSound; // +0x7c
    int32_t idleSoundChance; // +0x80
    int32_t alertSound; // +0x84
    int32_t attackSound; // +0x88
    int32_t hurtSound; // +0x8c
    int32_t deathSound; // +0x90
    int32_t allyType; // +0x94
    int32_t blocks; // +0x98
    int32_t d9c; // +0x9c
};

struct MonsterTableEntry { // original size 0x10
    MonsterStats * stats; // +0x0
    AnimSet * anim; // +0x4
    Texture * tex; // +0x8
    int32_t d0c; // +0xc
};

struct Wound { // original size 0x18
    int32_t active; // +0x0
    uint16_t color; // +0x4
    int16_t pad; // +0x6
    int32_t x0; // +0x8
    int32_t y0; // +0xc
    int32_t x1; // +0x10
    int32_t y1; // +0x14
};
static_assert(sizeof(Wound) == 0x18, "Wound must keep the original layout");

#pragma pack(push, 1)
struct MonsterCell { // original size 0x9
    uint8_t count; // +0x0
    uint8_t ids[8]; // +0x1
};
#pragma pack(pop)
static_assert(sizeof(MonsterCell) == 0x9, "MonsterCell must keep the original layout");

struct Door { // original size 0x12
    int16_t active; // +0x0
    int16_t level; // +0x2
    int16_t x; // +0x4
    int16_t y; // +0x6
    int16_t orient; // +0x8
    int16_t kind; // +0xa
    int16_t open; // +0xc
    int16_t lock; // +0xe
    int16_t timer; // +0x10
};
static_assert(sizeof(Door) == 0x12, "Door must keep the original layout");

struct InvSlot { // original size 0x4
    int16_t item; // +0x0
    int16_t qty; // +0x2
};
static_assert(sizeof(InvSlot) == 0x4, "InvSlot must keep the original layout");

struct PlayerStats { // original size 0x64
    char name[20]; // +0x0
    int32_t baseStr; // +0x14
    int32_t baseTou; // +0x18
    int32_t baseDex; // +0x1c
    int32_t baseInt; // +0x20
    int32_t str; // +0x24
    int32_t tou; // +0x28
    int32_t dex; // +0x2c
    int32_t intel; // +0x30
    int32_t hp; // +0x34
    int32_t maxHp; // +0x38
    int32_t mana; // +0x3c
    int32_t maxMana; // +0x40
    int32_t magicXp; // +0x44
    int32_t maxSpellLevel; // +0x48
    int32_t xp; // +0x4c
    int32_t level; // +0x50
    int32_t charClass; // +0x54
    int32_t s58; // +0x58
    int32_t portrait; // +0x5c
    float maxWeight; // +0x60
};
static_assert(sizeof(PlayerStats) == 0x64, "PlayerStats must keep the original layout");

struct Player { // original size 0xbc
    float x; // +0x0
    float y; // +0x4
    int32_t tileX; // +0x8
    int32_t tileY; // +0xc
    float destX; // +0x10
    float destY; // +0x14
    int32_t teleX; // +0x18
    int32_t teleY; // +0x1c
    int32_t angle; // +0x20
    int32_t turnAngle; // +0x24
    float depth; // +0x28
    float fxScale; // +0x2c
    int32_t sx; // +0x30
    int32_t sy; // +0x34
    int32_t rect[4]; // +0x38
    int32_t gameMode; // +0x48
    int32_t pendingAction; // +0x4c
    int32_t actionFrame; // +0x50
    int32_t animKind; // +0x54
    int32_t animFrame; // +0x58
    int32_t jumpCharge; // +0x5c
    int32_t p60; // +0x60
    int32_t jumpStep; // +0x64
    int32_t jumpSteps; // +0x68
    float jumpDist; // +0x6c
    int32_t currentSpell; // +0x70
    int32_t castSpell; // +0x74
    int32_t height; // +0x78
    uint32_t gold; // +0x7c
    int32_t arrows; // +0x80
    int32_t poisoned; // +0x84
    int32_t diseased; // +0x88
    int32_t diseaseTime; // +0x8c
    int32_t fatigue; // +0x90
    int32_t identify; // +0x94
    int32_t forceField; // +0x98
    int32_t stoneSkin; // +0x9c
    int32_t magicShield; // +0xa0
    uint32_t invisibility; // +0xa4
    int32_t resistUndead; // +0xa8
    int32_t restTime; // +0xac
    float speed; // +0xb0
    uint8_t attacking; // +0xb4
    uint8_t bowCooldown; // +0xb5
    uint8_t bb6; // +0xb6
    uint8_t bb7; // +0xb7
    int32_t noise; // +0xb8
};
static_assert(sizeof(Player) == 0xbc, "Player must keep the original layout");

struct Equipment { // original size 0x24
    int32_t weaponType; // +0x0
    int32_t ring1; // +0x4
    int32_t ring2; // +0x8
    int32_t e0c; // +0xc
    int32_t shield; // +0x10
    int32_t e14; // +0x14
    int32_t armourType; // +0x18
    int32_t e1c; // +0x1c
    int32_t difficulty; // +0x20
};
static_assert(sizeof(Equipment) == 0x24, "Equipment must keep the original layout");

struct Projectile { // original size 0x38
    int32_t active; // +0x0
    float x; // +0x4
    float y; // +0x8
    int32_t tileX; // +0xc
    int32_t tileY; // +0x10
    int32_t sx; // +0x14
    int32_t sy; // +0x18
    int32_t kind; // +0x1c
    int32_t flags; // +0x20
    int32_t angle; // +0x24
    int32_t timer; // +0x28
    float scale; // +0x2c
    int32_t power; // +0x30
    uint8_t light; // +0x34
};
static_assert(sizeof(Projectile) == 0x38, "Projectile must keep the original layout");

struct Rat { // original size 0x24
    float x; // +0x0
    float y; // +0x4
    int32_t sx; // +0x8
    int32_t sy; // +0xc
    int32_t tileX; // +0x10
    int32_t tileY; // +0x14
    uint8_t f18; // +0x18
    uint8_t state; // +0x19
    int32_t angle; // +0x1c
    uint8_t timer; // +0x20
    uint8_t light; // +0x21
};
static_assert(sizeof(Rat) == 0x24, "Rat must keep the original layout");

struct Servant { // original size 0x80
    int32_t active; // +0x0
    float x; // +0x4
    float y; // +0x8
    int32_t angle; // +0xc
    int32_t sx; // +0x10
    int32_t sy; // +0x14
    int32_t action; // +0x18
    int32_t counter; // +0x1c
    int32_t mode; // +0x20
    int32_t targetIdx; // +0x24
    int32_t wanderAngle; // +0x28
    Monster * target; // +0x2c
    float destX; // +0x30
    float destY; // +0x34
    int32_t life; // +0x38
    AnimSet anim; // +0x3c
    Model * model; // +0x78
    int32_t f7c; // +0x7c
};

#pragma pack(push, 2)
struct Trap { // original size 0x12
    int16_t level; // +0x0
    int16_t srcX; // +0x2
    int16_t srcY; // +0x4
    int16_t trigX; // +0x6
    int16_t trigY; // +0x8
    int16_t kind; // +0xa
    int16_t angle; // +0xc
    int32_t lastTime; // +0xe
};
#pragma pack(pop)
static_assert(sizeof(Trap) == 0x12, "Trap must keep the original layout");

#pragma pack(push, 2)
struct Feature { // original size 0xa
    int16_t active; // +0x0
    int16_t level; // +0x2
    int16_t x; // +0x4
    int16_t y; // +0x6
    int16_t sprite; // +0x8
};
#pragma pack(pop)
static_assert(sizeof(Feature) == 0xa, "Feature must keep the original layout");

#pragma pack(push, 2)
struct LevelItem { // original size 0xe
    int16_t active; // +0x0
    int16_t type; // +0x2
    int16_t level; // +0x4
    int16_t x; // +0x6
    int16_t y; // +0x8
    int16_t fa; // +0xa
    int16_t fc; // +0xc
};
#pragma pack(pop)
static_assert(sizeof(LevelItem) == 0xe, "LevelItem must keep the original layout");

struct Light { // original size 0x10
    int32_t f0; // +0x0
    int32_t f4; // +0x4
    int32_t f8; // +0x8
    int32_t fc; // +0xc
};
static_assert(sizeof(Light) == 0x10, "Light must keep the original layout");

#pragma pack(push, 2)
struct LevelAux { // original size 0x8
    int16_t level; // +0x0
    int16_t x; // +0x2
    int16_t y; // +0x4
    int16_t kind; // +0x6
};
#pragma pack(pop)
static_assert(sizeof(LevelAux) == 0x8, "LevelAux must keep the original layout");

struct SampleInfo { // original size 0xc
    const char * name; // +0x0
    uint8_t onDemand; // +0x4
    int32_t lastUsed; // +0x8
};

struct EVSound { // original size 0x18
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t sound; // +0xc
    int32_t playing; // +0x10
    Sound * dup; // +0x14
};

struct LevelObj { // original size 0x38
    uint8_t active; // +0x0
    int32_t level; // +0x4
    int32_t x; // +0x8
    int32_t y; // +0xc
    int32_t kind; // +0x10
    int32_t frame; // +0x14
    int32_t sx; // +0x18
    int32_t sy; // +0x1c
    int32_t w; // +0x20
    int32_t h; // +0x24
    int32_t x0; // +0x28
    int32_t y0; // +0x2c
    int32_t x1; // +0x30
    int32_t y1; // +0x34
};
static_assert(sizeof(LevelObj) == 0x38, "LevelObj must keep the original layout");

#pragma pack(push, 2)
struct Decal { // original size 0xe
    int16_t active; // +0x0
    int16_t level; // +0x2
    int16_t x; // +0x4
    int16_t y; // +0x6
    int16_t sprite; // +0x8
    int16_t fa; // +0xa
    int16_t fc; // +0xc
};
#pragma pack(pop)
static_assert(sizeof(Decal) == 0xe, "Decal must keep the original layout");

struct VisItem { // original size 0x1c
    int32_t idx; // +0x0
    int32_t sx; // +0x4
    int32_t sy; // +0x8
    int32_t rect[4]; // +0xc
};
static_assert(sizeof(VisItem) == 0x1c, "VisItem must keep the original layout");

struct VisFeature { // original size 0x68
    FGObject fg; // +0x0
    int32_t sprite; // +0x4c
    int32_t feature; // +0x50
    int32_t active; // +0x54
    int32_t rect[4]; // +0x58
};

struct VisDoor { // original size 0x30
    int32_t active; // +0x0
    int32_t door; // +0x4
    int32_t sx; // +0x8
    int32_t sy; // +0xc
    float depth1; // +0x10
    float depth2; // +0x14
    CSprite16 * sprA; // +0x18
    CSprite16 * sprB; // +0x1c
    int32_t rect[4]; // +0x20
};

struct WallEntry { // original size 0x24
    int32_t x; // +0x0
    int32_t y; // +0x4
    int32_t sx; // +0x8
    int32_t sy; // +0xc
    int32_t f10; // +0x10
    int32_t f14; // +0x14
    float depth; // +0x18
    int32_t sprite; // +0x1c
    uint8_t f20; // +0x20
};
static_assert(sizeof(WallEntry) == 0x24, "WallEntry must keep the original layout");

struct TileEntry { // original size 0x14
    int32_t x; // +0x0
    int32_t y; // +0x4
    int32_t sx; // +0x8
    int32_t sy; // +0xc
    int32_t overlay; // +0x10
};
static_assert(sizeof(TileEntry) == 0x14, "TileEntry must keep the original layout");

struct AnimTile { // original size 0x14
    int32_t x; // +0x0
    int32_t y; // +0x4
    int32_t kind; // +0x8
    int32_t frame; // +0xc
    int32_t counter; // +0x10
};
static_assert(sizeof(AnimTile) == 0x14, "AnimTile must keep the original layout");

struct Message { // original size 0x44
    char text[60]; // +0x0
    int16_t color; // +0x3c
    int16_t pad; // +0x3e
    int32_t time; // +0x40
};
static_assert(sizeof(Message) == 0x44, "Message must keep the original layout");

struct Container { // original size 0x48
    int16_t level; // +0x0
    int16_t pad; // +0x2
    int32_t pos[6]; // +0x4
    uint8_t type; // +0x1c
    uint8_t closed; // +0x1d
    uint8_t needsKey; // +0x1e
    uint8_t b1f; // +0x1f
    int32_t trapped; // +0x20
    int32_t examined; // +0x24
    InvSlot items[8]; // +0x28
};
static_assert(sizeof(Container) == 0x48, "Container must keep the original layout");

struct Sparkle { // original size 0x18
    uint8_t active; // +0x0
    uint8_t pad[3]; // +0x1
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t sx; // +0xc
    int32_t sy; // +0x10
    int32_t timer; // +0x14
};
static_assert(sizeof(Sparkle) == 0x18, "Sparkle must keep the original layout");

struct LevelLink { // original size 0x18
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t destLevel; // +0xc
    int32_t destX; // +0x10
    int32_t destY; // +0x14
};
static_assert(sizeof(LevelLink) == 0x18, "LevelLink must keep the original layout");

struct SignText { // original size 0x14
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    const char * text1; // +0xc
    const char * text2; // +0x10
};

struct Book { // original size 0x3c
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t x2; // +0xc
    int32_t y2; // +0x10
    int32_t pcx; // +0x14
    char file[10]; // +0x18
    char title[26]; // +0x22
};
static_assert(sizeof(Book) == 0x3c, "Book must keep the original layout");

struct WarpTile { // original size 0x14
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t destX; // +0xc
    int32_t destY; // +0x10
};
static_assert(sizeof(WarpTile) == 0x14, "WarpTile must keep the original layout");

struct TriggerSwitch { // original size 0x10
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    uint8_t state; // +0xc
    uint8_t want; // +0xd
    uint8_t pad0; // +0xe
    uint8_t pad1; // +0xf
};
static_assert(sizeof(TriggerSwitch) == 0x10, "TriggerSwitch must keep the original layout");

struct TriggerGroup { // original size 0x98
    int32_t type; // +0x0
    int32_t param; // +0x4
    TriggerSwitch sw[9]; // +0x8
};
static_assert(sizeof(TriggerGroup) == 0x98, "TriggerGroup must keep the original layout");

struct TrigWall { // original size 0xc
    int32_t x; // +0x0
    int32_t y; // +0x4
    uint8_t onTile; // +0x8
    uint8_t offTile; // +0x9
    uint8_t pad0; // +0xa
    uint8_t pad1; // +0xb
};
static_assert(sizeof(TrigWall) == 0xc, "TrigWall must keep the original layout");

struct TrigDoor { // original size 0xc
    int32_t x; // +0x0
    int32_t y; // +0x4
    int16_t lock; // +0x8
    int16_t pad; // +0xa
};
static_assert(sizeof(TrigDoor) == 0xc, "TrigDoor must keep the original layout");

struct TrigFeature { // original size 0xc
    int32_t x; // +0x0
    int32_t y; // +0x4
    int32_t sprite; // +0x8
};
static_assert(sizeof(TrigFeature) == 0xc, "TrigFeature must keep the original layout");

struct TrigWarp { // original size 0x1c
    int32_t level; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t offX; // +0xc
    int32_t offY; // +0x10
    int32_t onX; // +0x14
    int32_t onY; // +0x18
};
static_assert(sizeof(TrigWarp) == 0x1c, "TrigWarp must keep the original layout");

struct TrigPos { // original size 0x8
    int32_t x; // +0x0
    int32_t y; // +0x4
};
static_assert(sizeof(TrigPos) == 0x8, "TrigPos must keep the original layout");

struct SaveHeader { // original size 0x40
    int32_t version; // +0x0
    uint8_t key[32]; // +0x4
    char magic[4]; // +0x24
    char desc[21]; // +0x28
    uint8_t keyLen; // +0x3d
    uint8_t pad0; // +0x3e
    uint8_t pad1; // +0x3f
};
static_assert(sizeof(SaveHeader) == 0x40, "SaveHeader must keep the original layout");

struct Burner { // original size 0x20
    int32_t active; // +0x0
    int32_t x; // +0x4
    int32_t y; // +0x8
    int32_t kind; // +0xc
    int32_t state; // +0x10
    int32_t frame; // +0x14
    int32_t f18; // +0x18
    int32_t sprite; // +0x1c
};
static_assert(sizeof(Burner) == 0x20, "Burner must keep the original layout");

extern int32_t gLastTrack; // 0x43a148
extern const char * gConvTopics[42]; // 0x43a160
extern const char * gConvAnswers[208]; // 0x43a208
extern const char * gConvGreetings[46]; // 0x43a548
extern const char * gConvFarewells[18]; // 0x43a600
extern const char * gConvCostTexts[10]; // 0x43a648
extern ConvHeader gConvHeaders[12]; // 0x43a670
extern ConvNode gConvNodesInit[50]; // 0x43a790
extern int32_t gHotkeySlots[4]; // 0x43d7a0
extern const char * gMonsterNames[46]; // 0x43d7d0
extern MonsterStats gMonsterStats[46]; // 0x43d888
extern MonsterStats * gMonsterStatsTable[46]; // 0x43f548
extern SpawnRecord gSpawns[1250]; // 0x43f600
extern int32_t gDetourAngles[5]; // 0x447eb8
extern int32_t gGateXs[4]; // 0x447ed0
extern int32_t gGateYs[4]; // 0x447ee0
extern int32_t gFleeAngles[4]; // 0x447ef0
extern Vec3 gMoveProbes[3]; // 0x447f00
extern int32_t gHitSounds[66]; // 0x447f28
extern float gProjSpeed[10]; // 0x448350
extern Model * gProjModels[10]; // 0x448378
extern int32_t gProjFireSound[10]; // 0x4483a0
extern int32_t gProjExplodeTime[10]; // 0x4483c8
extern int32_t gProjExplodeSound[10]; // 0x4483f0
extern const char * gAppName; // 0x448a90
extern SampleInfo gSamples[106]; // 0x448c38
extern int32_t gFootstepSound[25]; // 0x4491e0
extern EVSound gEVSounds[6]; // 0x449248
extern int32_t gItemSpriteIdx[160]; // 0x449950
extern uint8_t gEquipSpriteIdx[180]; // 0x449bcf
extern int32_t gEquipRects[9][4]; // 0x449c88
extern int32_t gItemIconIdx[160]; // 0x449d18
extern int32_t gChestSlotX[8]; // 0x449f98
extern int32_t gChestSlotY[8]; // 0x449fb8
extern int32_t gObjSpriteFirst[24]; // 0x44a068
extern int32_t gObjSpriteLast[24]; // 0x44a0c8
extern int32_t gPulseLight; // 0x44a1b8
extern int32_t gPulseDir; // 0x44a1bc
extern int32_t gSparkleBounce[10]; // 0x44a1c0
extern int32_t gSpellRunes[90]; // 0x44a318
extern int32_t gLightFrameFirst[4]; // 0x44a480
extern int32_t gLightFrameLast[4]; // 0x44a490
extern int32_t gCastRollNoArmour[4]; // 0x44a4a0
extern int32_t gCastRollArmour[4]; // 0x44a4b0
extern int32_t gMissileSpread[8]; // 0x44a4c0
extern int32_t gCurseReplace[5]; // 0x44a4e0
extern int32_t gLocFxFirst[4]; // 0x44a4f8
extern int32_t gLocFxLen[4]; // 0x44a508
extern int32_t gTileRowOffset[32]; // 0x44a538
extern int32_t gTileRowWidth[32]; // 0x44a5b8
extern const char * gMsg[286]; // 0x44a650
extern const char * gItemNames[106]; // 0x44aac8
extern const char * gFeatureNames[98]; // 0x44ac70
extern const char * gObjNames[24]; // 0x44adf8
extern const char * gDoorNames[22]; // 0x44ae58
extern const char * gSpellNames[30]; // 0x44aeb0
extern SignText gSigns[54]; // 0x44af28
extern Book gBooks[9]; // 0x44b360
extern int32_t gDirDX[8]; // 0x44b650
extern int32_t gDirDY[8]; // 0x44b670
extern int32_t gDoorSounds[22]; // 0x44b6f0
extern int32_t gItemNameIdx[160]; // 0x44b748
extern int32_t gItemTrueNameIdx[160]; // 0x44b9c8
extern float gItemWeight[160]; // 0x44bc48
extern uint8_t gInvSortKeyRaw[151]; // 0x44bec7
extern uint8_t gBitMask[8]; // 0x44bf68
extern int32_t gFeatureNameIdx[400]; // 0x44bf70
extern int32_t gXpTable[16]; // 0x44c980
extern int32_t gSpellCost[6]; // 0x44ca28
extern int32_t gSpellXP[6]; // 0x44ca40
extern int32_t gMemorizeLimit[42]; // 0x44ca60
extern int32_t gCastEnd[30]; // 0x44cb28
extern int32_t gCastFireFrame[30]; // 0x44cba0
extern int32_t gCastSound[30]; // 0x44cc18
extern int32_t gCastSoundFrame[30]; // 0x44cc90
extern float gFearScale[16]; // 0x44cd08
extern int32_t gEquipX[9]; // 0x44cd48
extern int32_t gEquipY[9]; // 0x44cd70
extern uint8_t gEquipItemId[181]; // 0x44cd97
extern int32_t gWeaponDamage[22]; // 0x44ce50
extern int32_t gWeaponBreaks[22]; // 0x44cea8
extern int32_t gWeaponLevels[14]; // 0x44cf00
extern int32_t gArmourDefence[8]; // 0x44cf38
extern uint8_t gInit44d008[4000]; // 0x44d008
extern int32_t gCurseSlot[5]; // 0x44dfa8
extern int32_t gCurseItem[5]; // 0x44dfc0
extern uint8_t gInit44dfd8[9120]; // 0x44dfd8
extern TrigWall gTrigWalls[30][6]; // 0x450378
extern TrigDoor gTrigDoors[20]; // 0x450be8
extern TrigFeature gTrigFeatures[5][6]; // 0x450cd8
extern TrigWarp gTrigWarps[2]; // 0x450e40
extern TrigPos gTrigRemove[1][6]; // 0x450e78
extern LevelLink gLevelLinks[79]; // 0x450ea8
extern int32_t gShopItemsInit[36]; // 0x4516d8
extern int32_t gShopSlotX[12]; // 0x451768
extern int32_t gShopSlotY[12]; // 0x451798
extern int32_t gItemPrice[160]; // 0x4517c8
extern int32_t gLevelRatCount[25]; // 0x451a48
extern int32_t gLevelRatPoints[25]; // 0x451ab0
extern int32_t gLevelRatSpawns[250]; // 0x451b18
extern int32_t gZoneTable[60]; // 0x451f00
extern uint8_t gLevelObjsInit[8064]; // 0x452808
extern uint8_t gDecalsInit[8400]; // 0x454788
extern uint8_t gContainersInit[1872]; // 0x456858
extern uint8_t gTrapsInit[2250]; // 0x456fa8
extern char gCDDrive; // 0x457874
extern int32_t gSpellAnim[30]; // 0x457888
extern int32_t gSpellSparkle[30]; // 0x457900
extern Vec3 gPlayerProbes[3]; // 0x457978
extern char gClassLetters[4]; // 0x45799c
extern int32_t gArmourPatchIdx[8]; // 0x4579a0
extern const char * gArmourPatchName[4]; // 0x4579c0
extern int32_t gArmourPatchY[32]; // 0x4579d0
extern int32_t gBootsPatchIdx[4]; // 0x457a50
extern const char * gBootsPatchName[2]; // 0x457a60
extern int32_t gBootsPatchY[16]; // 0x457a68
extern int32_t gWeaponPatchIdx[22]; // 0x457aa8
extern const char * gWeaponPatchName[4]; // 0x457b00
extern int32_t gWeaponPatchY[84]; // 0x457b10
extern int32_t gShieldPatchIdx[4]; // 0x457c60
extern const char * gShieldPatchName[4]; // 0x457c70
extern int32_t gShieldPatchY[16]; // 0x457c80
extern const char * gPlayerTexDir; // 0x457cc0
extern int32_t gFatigueLevels[5]; // 0x45b2c8
extern int32_t gHpDice[4]; // 0x45b2e0
extern const char * gBookPcxNames[3]; // 0x45b2f0
extern int32_t gLightSpellBright[3]; // 0x45b320
extern int32_t gLightSpellRadius[3]; // 0x45b330
extern int32_t gStatusY; // 0x45b578
extern int32_t gAmbientTimer; // 0x45b66c
extern int32_t gManaRegenPeriod[4]; // 0x45b670
extern uint8_t gTrapOverlay[25]; // 0x45b680
extern int32_t gStatueItems[6]; // 0x45b6a0
extern int32_t gMusicDelay; // 0x45e4e4
extern int32_t gConvCost; // 0x45e4e8
extern int32_t gConvResult; // 0x45e4ec
extern ConvNode gConvNodes[50]; // 0x45e4f0
extern uint8_t gConvMenuInit; // 0x45ea68
extern Sprite * gConvBackground; // 0x45ea6c
extern MenuItem gConvMenu[13]; // 0x45ea78
extern Wound gWounds[10]; // 0x45ec80
extern char gHotkeyText[10][80]; // 0x45ed78
extern int32_t gSpellHotkeys[10]; // 0x45f0e8
extern PCX gHotkeyPCX; // 0x45f110
extern MenuItem gHotkeyMenu[11]; // 0x45f1c8
extern int32_t gHotkeyPage; // 0x45f380
extern Bolt gBolts[30]; // 0x45f388
extern int32_t gHostileCount; // 0x46099c
extern int32_t gNumMonsterTables; // 0x4609a0
extern Monster gMonsters[1250]; // 0x4609a8
extern MonsterTableEntry gMonsterTables[8]; // 0x4a4f68
extern AnimSet gMonsterAnims[8]; // 0x4a4fe8
extern MonsterCell gMonsterMap[4550]; // 0x4a51c8
extern Texture gMonsterTextures[10]; // 0x4af1c0
extern Model gRatModel; // 0x4af4c8
extern Texture gRatTex; // 0x4af510
extern Rat gRats[30]; // 0x4af528
extern int32_t gNumRats; // 0x4af960
extern Texture gServantTex; // 0x4af968
extern AnimSet gServantAnim; // 0x4af980
extern void * gHwnd; // 0x4b18e8
extern int32_t gRunning; // 0x4b18f4
extern void * gHInstance; // 0x4b18f8
extern int32_t gAppActive; // 0x4b1900
extern int32_t gModelError; // 0x4b89e8
extern int32_t gSavedWaveVolume; // 0x4be148
extern SndDevice * gDSound; // 0x4be1a0
extern int32_t gEVTimer; // 0x4be1a4
extern Sound * gSoundBufs[106]; // 0x4be1a8
extern Sound * gSpeech; // 0x4be350
extern int32_t gEVRunning; // 0x4be3b0
extern int32_t gEVBusy; // 0x4be3b4
extern int32_t gClockTimer; // 0x4be430
extern int32_t gTime; // 0x4be434
extern uint8_t gClockRunning; // 0x4be438
extern Model gCGModels[4]; // 0x4be4c8
extern Texture gCGTex[4]; // 0x4be5d8
extern PCX gChargenPCX; // 0x4be638
extern PCX gPCX2; // 0x4be6f0
extern int32_t gZoneEnd; // 0x4be8f8
extern int32_t gWallRects[600][4]; // 0x4be908
extern float gFGMaxDepth; // 0x4bf588
extern int32_t gVisRestart; // 0x4bf5a0
extern float gFGMinDepth; // 0x4bf630
extern int32_t gFGRendering; // 0x4bf638
extern int32_t gEffectShown[6]; // 0x4bf640
extern int32_t gZoneFirst; // 0x4bf658
extern int32_t gHordeCount; // 0x4bf660
extern int32_t gTargetAngle; // 0x4bf664
extern MenuItem gCastMenu[8]; // 0x4bf670
extern MenuItem gSpellLevelMenu[7]; // 0x4bf7b0
extern MenuItem gActionMenu[8]; // 0x4bf8c8
extern int32_t gMemorizePage; // 0x4bfa08
extern int32_t gCastPage; // 0x4bfa0c
extern int32_t gLocFxAngle; // 0x4bfa10
extern uint16_t gPalette555[256]; // 0x4bfa18
extern int32_t gItemHover; // 0x53c188
extern uint32_t gTicks; // 0x53c190
extern Model * gPlayerModel; // 0x53c194
extern PCX gRunesPCX; // 0x53c198
extern CSprite16 gRuneSprites[30]; // 0x53c250
extern char gPlayerAmtName[24]; // 0x53c438
extern LevelAux gLevelAux[400]; // 0x53c450
extern uint32_t gFrameCounter; // 0x53d0d0
extern CSprite16 gDoorSprites[650]; // 0x53d0d8
extern int32_t gFeatFirst; // 0x53f978
extern int8_t gSpellsMemorized[30]; // 0x53f980
extern int32_t gNumMessages; // 0x53f9a8
extern Texture gLightningTex; // 0x53f9b0
extern float gShownMana; // 0x53f9c4
extern int32_t gAltView; // 0x53f9c8
extern int32_t gLightSpell; // 0x53f9d0
extern int32_t gLightKind; // 0x53f9d4
extern int32_t gLightFrame; // 0x53f9dc
extern int32_t gLightSx; // 0x53f9e0
extern int32_t gLightSy; // 0x53f9e4
extern int32_t gAttackRequest; // 0x53f9e8
extern Model gMissileModel; // 0x53f9f0
extern CDAudio gCD; // 0x53fa38
extern uint16_t gColorGrey128; // 0x53fa50
extern int32_t gDeepestLevel; // 0x53fa54
extern Log gLog; // 0x53fa58
extern int32_t gMusicSound; // 0x53fb5c
extern int32_t gFGCount; // 0x53fb60
extern PlayerStats gStats; // 0x53fb68
extern Feature gFeatures[875]; // 0x53fbd0
extern Texture gPlayerTexture; // 0x541e00
extern Burner gBurners[4]; // 0x541e18
extern DirectDrawWindow gDDW; // 0x541e98
extern int32_t gFloorCacheHits; // 0x541f38
extern char gLevelName[25][16]; // 0x541f40
extern Equipment gEquip; // 0x5420d0
extern CSprite16 gMapSprites[30]; // 0x5420f8
extern uint8_t * gLevelLayout[25]; // 0x5422d8
extern int32_t gScreenCount; // 0x54233c
extern LevelObj gLevelObjs[200]; // 0x571140
extern TriggerGroup gTriggers[60]; // 0x573d00
extern uint16_t gBaseLight[4550]; // 0x5760a0
extern float gShownHp; // 0x57842c
extern FGObject gFGPool[900]; // 0x578430
extern int32_t gSavedHudVisible; // 0x57ec18
extern uint8_t gTrapActive; // 0x57ec20
extern int32_t gTrapFrame; // 0x57ec24
extern float gTrapX; // 0x57ec28
extern float gTrapY; // 0x57ec2c
extern int32_t gTrapSx; // 0x57ec30
extern int32_t gTrapSy; // 0x57ec34
extern int32_t gTorchFuel; // 0x57ec38
extern uint16_t gColorNearBlack; // 0x57ec44
extern double gTickRate; // 0x57ec50
extern uint8_t * gWallLayer; // 0x57ec5c
extern float gRunSpeed; // 0x57ec60
extern uint8_t * gLevelTiles[25]; // 0x57ec68
extern Trap gTraps[125]; // 0x5963d0
extern FGObject gFGHead; // 0x596ca0
extern Texture gBoltTex; // 0x596cf0
extern int32_t gDecalMap[4550]; // 0x596d08
extern CSprite16 gFloorSprites[240]; // 0x59b420
extern LevelItem gLevelItems[1501]; // 0x59c320
extern uint8_t gAutomap[16250]; // 0x5a1528
extern uint8_t gKeyBuf[2]; // 0x5a54a4
extern WarpTile gWarps[200]; // 0x5a54a8
extern CSprite16 g_5a6448[20]; // 0x5a6448
extern float gShownMaxMana; // 0x5a6588
extern uint8_t g_5a6590; // 0x5a6590
extern uint8_t gMetJetraal; // 0x5a6591
extern uint8_t g_5a6593; // 0x5a6593
extern uint8_t gTalkedToPriest; // 0x5a6594
extern uint8_t gMetGremlins; // 0x5a6595
extern uint8_t gGremlinsGotOrb; // 0x5a6596
extern int32_t g_5a6598; // 0x5a6598
extern int16_t g_5a659c; // 0x5a659c
extern uint8_t g_5a659e; // 0x5a659e
extern int32_t gTarget; // 0x5a65a0
extern int32_t gWallCount; // 0x5a65a4
extern uint8_t * gLevelMap; // 0x5a65a8
extern int32_t gNumAux; // 0x5a65ac
extern int32_t gMouseX; // 0x5a65b0
extern char gStatusText[60]; // 0x5a65b8
extern int32_t gShopScroll; // 0x5a65f4
extern Message gMessages[6]; // 0x5a6600
extern Container gContainers[50]; // 0x5a67a8
extern int32_t gChestSpriteCount; // 0x5a75b8
extern Sparkle gSparkles[20]; // 0x5a75c0
extern CSprite16 gFaces[25]; // 0x5a7818
extern int32_t gPads[20][2]; // 0x5a79a8
extern char gInfoText[12][50]; // 0x5a7a50
extern uint16_t gColorRed; // 0x5a7d40
extern uint8_t gObjSpriteUsed[400]; // 0x5a7d48
extern int32_t gActionMode; // 0x5a7ed8
extern TileEntry gTiles[1600]; // 0x5a7ee0
extern int32_t gFaceCount; // 0x5aa9dc
extern int32_t gMouseY; // 0x5aa9e0
extern int32_t gNumLights; // 0x5aa9f0
extern int32_t gInvScroll; // 0x5aa9f4
extern int32_t gFeatLast; // 0x5aa9f8
extern uint16_t gColorAzure; // 0x5aa9fc
extern Prefs gPrefs; // 0x5aaa00
extern int32_t gUIMode; // 0x5aaa28
extern int32_t gFeatureSpriteCount; // 0x5aaa2c
extern int32_t gObjFirst; // 0x5aaa30
extern int32_t gViewLeft; // 0x5aaa38
extern int32_t gViewTop; // 0x5aaa3c
extern int32_t gViewRight; // 0x5aaa40
extern int32_t gViewHeight; // 0x5aaa44
extern Model gHordeModel; // 0x5aaa48
extern int32_t gLoadTime; // 0x5aaa8c
extern Clipper gClip; // 0x5aaa98
extern int32_t gWallSpriteCount; // 0x5aaab0
extern Decal gDecals[600]; // 0x5aaab8
extern int32_t gShopItems[36]; // 0x5acb90
extern int32_t gBarCount; // 0x5acc20
extern int32_t gTimeStop; // 0x5acc24
extern int32_t gDrainTime; // 0x5acc28
extern VisDoor gVisDoors[36]; // 0x5acc30
extern int32_t gFloorCacheProbes; // 0x5ace78
extern float gCamX; // 0x5ace7c
extern float gCamY; // 0x5ace80
extern uint8_t * gLevelWalls[25]; // 0x5ace88
extern int32_t gFootstepTimer; // 0x5aceec
extern int32_t gBloodCount; // 0x5acef0
extern SpriteTable gActionSprites; // 0x5acef8
extern Model gSummonModel; // 0x5ad8a8
extern uint8_t * gOverlayLayer; // 0x5ad8ec
extern int32_t gObjLast; // 0x5ad8f0
extern int32_t gDoorHover; // 0x5ad8f4
extern int32_t gPathActive; // 0x5ad8f8
extern uint8_t * gRegionLayer; // 0x5ad8fc
extern int32_t gInvCount; // 0x5ad900
extern int32_t gActionCount; // 0x5ad904
extern int32_t g_5ad908; // 0x5ad908
extern int32_t gTrapSpriteCount; // 0x5ad90c
extern int32_t g_5ad910; // 0x5ad910
extern int32_t gGodMode; // 0x5ad914
extern Player gPlayer; // 0x5ad918
extern CSprite16 gScreenSprites[50]; // 0x5ad9d8
extern Font gFontSmall; // 0x5add00
extern int32_t gMapWidth; // 0x5adf08
extern int32_t gLevelH[25]; // 0x5adf10
extern CSprite16 gSparkleSprites[10]; // 0x5adf78
extern int32_t gLoopFrames; // 0x5ae018
extern Texture gHordeTex; // 0x5ae020
extern int32_t gAnimSpriteCount; // 0x5ae034
extern Texture gFireballTex; // 0x5ae038
extern int32_t gDoorSpriteCount; // 0x5ae04c
extern int32_t gItemIconCount; // 0x5ae050
extern int32_t gHudFlags; // 0x5ae054
extern int32_t gItemSpriteCount; // 0x5ae058
extern CSprite16 gFeatureSprites[400]; // 0x5ae060
extern CSprite16 gAnimSprites[50]; // 0x5af960
extern int32_t gItemLast; // 0x5afc80
extern Texture gSummonTex; // 0x5afc88
extern int32_t gBusyCursor; // 0x5afc9c
extern Shade16 gShade; // 0x5afca0
extern int32_t gLeftClick; // 0x5afd38
extern int32_t gLocFxActive; // 0x5afd40
extern int32_t gLocFxKind; // 0x5afd44
extern float gLocFxX; // 0x5afd48
extern float gLocFxY; // 0x5afd4c
extern int32_t gLocFxSprite; // 0x5afd58
extern float gLocFxDepth; // 0x5afd5c
extern int32_t gLocFxFrame; // 0x5afd60
extern int32_t gLocFxUnused; // 0x5afd64
extern int32_t gFeatureHover; // 0x5afd68
extern int32_t gNumVisItems; // 0x5afd6c
extern uint8_t * gLevelAltWalls[25]; // 0x5afd70
extern int32_t gWeaponFlag; // 0x5afdd4
extern VisFeature gVisFeatures[500]; // 0x5afde0
extern uint32_t gFloorCacheMax; // 0x5b4f20
extern uint16_t gColorGrey96; // 0x5b4f28
extern int32_t gViewOffX; // 0x5b4f2c
extern int32_t gViewOffY; // 0x5b4f30
extern uint16_t gColorWhite; // 0x5b4f34
extern float gShownMaxHp; // 0x5b4f38
extern int32_t gLevelLoaded; // 0x5b4f3c
extern int32_t gCurLevel; // 0x5b4f40
extern CSprite16 gArmsSprites[50]; // 0x5b4f48
extern int32_t g_5b5268; // 0x5b5268
extern Projectile gProjectiles[10]; // 0x5b5270
extern int32_t gInfoLines; // 0x5b54a0
extern uint16_t gColorBlue; // 0x5b54a4
extern CSprite16 gEquipSprites[100]; // 0x5b54a8
extern Light gLights[750]; // 0x5b5ae8
extern int32_t gFlashColor; // 0x5b89cc
extern int32_t gLevelW[25]; // 0x5b89d0
extern uint8_t gFeatureSpriteUsed[400]; // 0x5b8a38
extern char gLevelDesc[25][32]; // 0x5b8bc8
extern Texture gMissileTex; // 0x5b8ee8
extern uint8_t gDoorSpriteUsed[650]; // 0x5b8f00
extern AnimSet gPlayerAnim; // 0x5b9190
extern Servant gServants[10]; // 0x5b91d0
extern SpriteTable gHudSprites; // 0x5b96d0
extern VisItem gVisItems[600]; // 0x5ba080
extern Model gFireballModel; // 0x5bc150
extern int32_t g_5bc194; // 0x5bc194
extern int32_t gSpellFxCount; // 0x5bc19c
extern int32_t gDoorFirst; // 0x5bc1a0
extern Text gText; // 0x5bc1a8
extern int32_t gLightRadius; // 0x5bc1dc
extern int32_t gInfoX; // 0x5bc1e0
extern int32_t gInfoY; // 0x5bc1e4
extern int32_t gItemFirst; // 0x5bc1e8
extern int32_t gRegenTime; // 0x5bc1ec
extern WallEntry gWalls[600]; // 0x5bc1f0
extern int32_t gHintButton; // 0x5bde10
extern int32_t g_5be7c4; // 0x5be7c4
extern AnimTile gAnimTiles[160]; // 0x5be7c8
extern int32_t gStatuesDestroyed; // 0x5bf448
extern CSprite16 gEffectSprites[120]; // 0x5bf450
extern uint8_t gMapVis[4550]; // 0x5bfbd0
extern int32_t gArmsCount; // 0x5c0d98
extern int32_t gMapHeight; // 0x5c0d9c
extern int32_t gDoorLast; // 0x5c0da0
extern char gLevelTitle[25][16]; // 0x5c0da8
extern int32_t gPrevActionMode; // 0x5c0f38
extern int32_t gLightLast; // 0x5c0f3c
extern int32_t gObjSpriteCount; // 0x5c0f44
extern CSprite16 gItemSprites[100]; // 0x5c0f48
extern uint8_t gRuneCounts[26]; // 0x5c1588
extern Model gBoltModel; // 0x5c15a8
extern Door gDoors[400]; // 0x5c15f0
extern InvSlot gInventory[30]; // 0x5c3210
extern int32_t gMapRow[66]; // 0x5c3290
extern Model gLightningModel; // 0x5c3398
extern uint16_t gDynLight[4550]; // 0x5c33e0
extern PCX gCharPCX; // 0x5c5770
extern int32_t g_5c5824; // 0x5c5824
extern int32_t gStatusTimer; // 0x5c5828
extern uint32_t gFloorCount; // 0x5c5834
extern int32_t gLightBright; // 0x5c5838
extern int32_t gHaveMap; // 0x5c5840
extern int32_t gFloorCacheMisses; // 0x5c5844
extern int32_t gLightFirst; // 0x5c5848
extern CSprite16 gItemIcons[100]; // 0x5c5850
extern CSprite16 gObjSprites[400]; // 0x5c5e90
extern CSprite16 gWallSprites[200]; // 0x5c7798
extern CSprite16 gDecalSprites[60]; // 0x5c8418
extern uint16_t gLightMap[4550]; // 0x5c87d8
extern int32_t g_5cab64; // 0x5cab64
extern uint16_t gColorGreen; // 0x5cab68
extern float gWalkSpeed; // 0x5cab6c
extern int32_t gHudVisible; // 0x5cab70
extern int32_t gTileCount; // 0x5cab74
extern FGObject gFGTail; // 0x5cab80
extern Font gFontLarge; // 0x5cabd0
extern int32_t gPickList[10]; // 0x5cade0
extern CSprite16 g_5cae08[15]; // 0x5cae08
extern MenuItem gPickMenu[11]; // 0x5caf00
extern MenuItem gOptionsMenu[11]; // 0x5cb0b8
extern MenuItem gShadowMenu[8]; // 0x5cb270
extern int32_t gNewWalkTarget; // 0x5cb3b0
extern PCX gChestPCX; // 0x5cb3b8
extern Sprite * gChestSave; // 0x5cb46c
extern int32_t gSaveMenuCount; // 0x5cb478
extern int32_t gSaveMisc[40]; // 0x5cb480
extern SaveHeader gSaveHeaders[10]; // 0x5cb548
extern Sprite * gStatusSave; // 0x5cb7cc
extern MenuItem gSaveMenu[11]; // 0x5cb7d0
